"use strict";

module.exports = {
  "react-hooks/exhaustive-deps": "error",
  "react-hooks/rules-of-hooks": "error",
  "react/button-has-type": "error",
  "react/default-props-match-prop-types": "error",
  "react/jsx-fragments": "error",
  "react/jsx-key": "error",
  "react/jsx-no-comment-textnodes": "error",
  "react/jsx-no-duplicate-props": "error",
  "react/jsx-no-target-blank": "error",
  "react/jsx-no-undef": "error",
  "react/jsx-pascal-case": ["error", { allowAllCaps: true }],
  "react/jsx-uses-react": "error",
  "react/jsx-uses-vars": "error",
  "react/no-danger-with-children": "error",
  "react/no-deprecated": "error",
  "react/no-direct-mutation-state": "error",
  "react/no-find-dom-node": "error",
  "react/no-is-mounted": "error",
  "react/no-render-return-value": "error",
  "react/no-string-refs": "error",
  "react/no-typos": "error",
  "react/no-unescaped-entities": "error",
  "react/no-unknown-property": "error",
  "react/no-unsafe": "error",
  "react/no-unused-prop-types": "error",
  "react/no-unused-state": "error",
  "react/prop-types": "error",
  "react/react-in-jsx-scope": "error",
  "react/require-default-props": "off",
  "react/require-render-return": "error",
  "react/style-prop-object": "error",
};
